hubblecommerce/hubble-frontend-pwa

@hubblecommerce/hubble/core/components/productlist/ViewCategory.vue
improves performance because components are imported only when needed
closes #2
=> include components as dynamic imports

@hubblecommerce/hubble/core/components/checkout/CartItemsList.vue
=> issue#11 Edited CartItmList.vue: added selfclosing tag, dynamic imports and change v-html

@hubblecommerce/hubble/core/components/checkout/CheckoutProgressBar.vue
=> issue#17 Edited CheckoutProgressBar.vue: added selfclosing tag and v-text

@hubblecommerce/hubble/core/components/checkout/Totals.vue
Totals.vue: added v-text and selfclosing tags.
=> issue#19 Edited Totals.vue: added v-text and selfclosing tags

@hubblecommerce/hubble/core/components/productdetail/ViewProduct.vue
=> issue#13 replace v-html with v-text and delete commented out code

@hubblecommerce/hubble/core/components/customer/LoginForm.vue, @hubblecommerce/hubble/core/locales/de.js, @hubblecommerce/hubble/core/locales/en.js
Switched german text to english for consistent english code.
=> issue#22 Edited LoginForm.vue: Switched german text to english.

@hubblecommerce/hubble/core/components/productdetail/ProductDetailGallery.vue
=> issue#25 changed img tags to img-lazy tags

@hubblecommerce/hubble/core/components/customer/CustomerAccountInformation.vue
=> issue#27 Edited CustomerAccounInformation.vue: Added v-text and selfclosing tags.

@hubblecommerce/hubble/core/components/footer/TheFooterMobile.vue
=> issue#31 changed img to img-lazy, changed component to dynamic import

@hubblecommerce/hubble/core/components/footer/TheFooterDesktop.vue
=> issue#33 changed alt to alt-info, added title-info to img-lazy tags

@hubblecommerce/hubble/core/components/navigation/TheMobileMenu.vue
=> issue#37 Edited TheMobileMenu.vue: added dynamic imports of components

@hubblecommerce/hubble/core/components/productlist/ProductListingCard.vue
=> issue#41 Replaced v-html with v-text, deleted commented out code and replaced anchor tag with nuxt-link

@hubblecommerce/hubble/core/components/navigation/CartLayer.vue
=> issue#29 Edited CartLayer.vue: added v-text, selfclosing tags and dynamic import

@hubblecommerce/hubble/core/components/navigation/WishlistLayer.vue
=> issue#35 Edited WishlistLayer.vue: added v-text and dynamic import of component.

@hubblecommerce/hubble/core/components/productlist/ViewCategory.vue, @hubblecommerce/hubble/core/store/sw/modApiCategory.js
=> issue#39 deleted commented out code, deleted redundancy

@hubblecommerce/hubble/core/components/customer/WishlistItemsList.vue
=> issue#43 Edited WishlistItemsList.vue: Adjusting v-text and img-lazy 

@hubblecommerce/hubble/core/components/productlist/toolbar/PriceSlider.vue
=> issue#46 changed v-html to v-text

@hubblecommerce/hubble/core/components/productlist/toolbar/Pagination.vue, @hubblecommerce/hubble/core/locales/de.js, @hubblecommerce/hubble/core/locales/en.js
=> issue#48 made tags self closing, changed static text to be translatable and made entries in locales

@hubblecommerce/hubble/core/pages/customer/wishlist.vue
=> issue#50 Edited wishlist.vue: Adjusted path to missing action, added v-text and dynamic imports.

@hubblecommerce/hubble/core/components/productlist/ProductListingFilter.vue
=> issue#52 deleted commented out code and changed imports to be dynamic

@hubblecommerce/hubble/core/components/productdetail/ProductDetailAddToCart.vue
=> issue#54 changed span tag to self closing and Loader component to import dynamically

@hubblecommerce/hubble/core/assets/scss/hubble/components/cookie-notice.scss, @hubblecommerce/hubble/core/components/utils/CookieNotice.vue, @hubblecommerce/hubble/core/locales/de.js, @hubblecommerce/hubble/core/locales/en.js
=> Issue#10 changed text to be translatable, change tags to be self closing, removed redundacy by handling media queries in scss

@hubblecommerce/hubble/core/assets/scss/hubble/components/add-to-wishlist.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-buybox.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/view-product.scss, @hubblecommerce/hubble/core/components/productdetail/ProductDetailBuybox.vue, @hubblecommerce/hubble/core/components/productdetail/ViewProduct.vue
=> Issue#68 Edited ViewProduct.vue: added Wishlist-Button to desktop-view, added dynamic imports

@hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-gallery.scss, @hubblecommerce/hubble/core/components/productdetail/ProductDetailGallery.vue
=> issue#70 Edited ProductDetailGallery.vue + .scss: deleted unused code

@hubblecommerce/hubble/core/assets/scss/hubble/all.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing-toolbar.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/selectable-order.scss, @hubblecommerce/hubble/core/components/productlist/toolbar/SelectableOrder.vue
=> issue#77 changed tag to self closing, created scss file

@hubblecommerce/hubble/core/assets/scss/hubble/all.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-header-actions.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/view-product.scss, @hubblecommerce/hubble/core/components/productdetail/ProductDetailHeaderActions.vue
=> Issue#76 Refactored ProductDetailHeaderActions.vue

@hubblecommerce/hubble/core/components/utils/Tabs.vue
=> issue#72 deleted redundant code

@hubblecommerce/hubble/core/components/productlist/ProductListingCard.vue
=> issue#74 changed tags to self closing, deleted 1 img tag and made the class of the other tag to be depended on the isSlider prop

@hubblecommerce/hubble/core/assets/scss/hubble/all.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing-toolbar.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/selectable-limit.scss, @hubblecommerce/hubble/core/components/productlist/toolbar/SelectableLimit.vue
=> issue#80 changed tag to self-closing, created scss

@hubblecommerce/hubble/core/components/productlist/toolbar/Pagination.vue
=> issue#85 changed Previous to Previous Page

@hubblecommerce/hubble/core/components/checkout/CartItemsListNonInteractive.vue
=> issue#82 Edited CartIemsListNonInteractive.vue: added v-text, selfclosing tags and img-lazy

@hubblecommerce/hubble/core/components/customer/OrderDetail.vue
=> issue#87 Edited OrderDetail.vue: added v-text and dynamic import

@hubblecommerce/hubble/core/assets/scss/hubble/all.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-buybox.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-manufacturer.scss, @hubblecommerce/hubble/core/components/productdetail/ProductDetailManufacturer.vue
=> issue#88 changed img to img-lazy, v-html to v-text, created scss file, removed data and methods and changed the way the img src is used

@hubblecommerce/hubble/core/assets/scss/hubble/components/cart-items-list.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/qty-selector.scss, @hubblecommerce/hubble/core/components/checkout/CartItemsList.vue
=> Issue#93 Edited qty-selector.scss and cartItemsList to fix qty-position

@hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/view-category.scss, @hubblecommerce/hubble/core/components/productlist/ProductListing.vue
=> Issue#97 Refactoring ProductListing

@hubblecommerce/hubble/core/assets/scss/hubble/components/add-to-wishlist.scss
=> issue#99 Edited add-to-wishlist.scss: adjusted styles to keep background

@hubblecommerce/hubble/core/assets/scss/hubble/components/product-detail-buybox.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/view-product.scss, @hubblecommerce/hubble/core/components/productdetail/ProductDetailAddToCart.vue, @hubblecommerce/hubble/core/components/productdetail/ProductDetailBuybox.vue
=> issue#95 Edited ProductDetailAddtoCart.vue: fixed jumping cart-icon

@hubblecommerce/hubble/core/assets/scss/hubble/components/hubble.scss, @hubblecommerce/hubble/core/components/utils/LayoutWrapper.vue
=> Issue#4 Fixed jumping content when scroll disabled

@hubblecommerce/hubble/core/assets/scss/hubble/components/pagination.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing-toolbar.scss
Created Pull request for review.
=> Issue#105 Pagination: Adjusting Styles 

@hubblecommerce/hubble/core/components/productlist/OffcanvasFilter.vue
=> issue#108 changed imports to dynamic, deleted commented out code, deleted unused vuex mutations imports

@hubblecommerce/hubble/core/components/productlist/ProductListingToolbar.vue
=> issue#110 changed imports to be dynamic

@hubblecommerce/hubble/core/assets/scss/hubble/components/offcanvas-filter.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/price-slider.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing-filter.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/product-listing-toolbar.scss, @hubblecommerce/hubble/core/assets/scss/hubble/components/view-category.scss, @hubblecommerce/hubble/core/components/productlist/ProductListingFilter.vue, @hubblecommerce/hubble/core/components/productlist/toolbar/PriceSlider.vue, @hubblecommerce/hubble/core/components/productlist/toolbar/SelectableFacet.vue, @hubblecommerce/hubble/core/components/utils/Collapsible.vue, @hubblecommerce/hubble/core/locales/de.js, @hubblecommerce/hubble/core/locales/en.js
=> Issue#104 Listing Filter / PriceSlider Style-Adjustments

src/platforms/shopware/api-client/utils/dataMapping.ts
=> issue#136 SW API Client: navigation mapping

__tests__/module/fixture/pages/index.vue, package-lock.json, package.json, vitest.config.ts
=> Issue#140 Fix tests 
